apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: p1jro96sb-nodejs-gitops
  description: This is GitOps manifest for p1jro96sb-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: p1jro96sb-nodejs
    janus-idp.io/tekton: p1jro96sb-nodejs 
    backstage.io/kubernetes-id: p1jro96sb-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:p1jro96sb-nodejs
